# Generated by Django 4.1.7 on 2023-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0015_stripesubscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
