# Generated by Django 4.1.7 on 2023-10-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0020_alter_feepaid_vendorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaid',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
