# Generated by Django 4.2.1 on 2023-10-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0023_alter_feepaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaid',
            name='influ_amount',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='feepaid',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
