# Generated by Django 4.2.5 on 2023-11-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0025_alter_feepaid_influ_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaid',
            name='campaign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CampaignApp.vendorcampaign'),
        ),
    ]
