# Generated by Django 4.2.5 on 2023-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0026_feepaid_campaign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modashinfluencer',
            name='paid_status',
            field=models.BooleanField(default=0),
        ),
    ]
