# Generated by Django 3.2.10 on 2024-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0027_modashinfluencer_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='camp_images/'),
        ),
    ]
