# Generated by Django 3.2.10 on 2024-01-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampaignApp', '0028_campaign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
    ]
