# Generated by Django 4.1.7 on 2023-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_remove_stripe_details_publishable_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
