# Generated by Django 4.1.7 on 2023-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_user_bank_account_user_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
