# Generated by Django 4.1.7 on 2023-10-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerdetails',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerdetails',
            name='fee',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
