# Generated by Django 4.1.7 on 2023-10-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerApp', '0002_influencerdetails_bank_account_influencerdetails_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerdetails',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='influencerdetails',
            name='fee',
        ),
    ]
